# frozen_string_literal: true

require_relative 'array/join'
require_relative 'array/join_post'
require_relative 'array/join_pre'
require_relative 'case/back_slash'
require_relative 'case/camel'
require_relative 'case/constant'
require_relative 'case/dash'
require_relative 'case/dot'
require_relative 'case/double_colon'
require_relative 'case/human'
require_relative 'case/lamel'
require_relative 'case/lower'
require_relative 'case/slash'
require_relative 'case/snake'
require_relative 'case/title'
require_relative 'case/upper'
require_relative 'comparison/and'
require_relative 'comparison/default'
require_relative 'comparison/eq'
require_relative 'comparison/gt'
require_relative 'comparison/gte'
require_relative 'comparison/lt'
require_relative 'comparison/lte'
require_relative 'comparison/ne'
require_relative 'comparison/or'
require_relative 'inflection/ordinal'
require_relative 'inflection/ordinalize'
require_relative 'inflection/pluralize'
require_relative 'inflection/pluralize_number'
require_relative 'inflection/pluralize_number_word'
require_relative 'inflection/singularize'
require_relative 'misc/format_json'
# require_relative 'misc/omit'
require_relative 'misc/safe'
require_relative 'str/padl'
require_relative 'str/padr'
