# frozen_string_literal: true

require_relative 'array/join'
require_relative 'array/join_post'
require_relative 'array/join_pre'
require_relative 'comparison/and'
require_relative 'comparison/default'
require_relative 'comparison/eq'
require_relative 'comparison/gt'
require_relative 'comparison/gte'
require_relative 'comparison/lt'
require_relative 'comparison/lte'
require_relative 'comparison/ne'
require_relative 'comparison/or'
require_relative 'inflection/ordinal'
require_relative 'inflection/ordinalize'
require_relative 'inflection/pluralize'
require_relative 'inflection/pluralize_by_number'
require_relative 'inflection/singularize'
